// pipeline {
//   agent any
//   tools {
//     maven 'maven' 
//   }
//   stages {
//     stage ('Init') {
//       steps {
//         sh 'echo "Start of Job"'
//         sh 'ls -la'
//       }
//     }
//     stage ('test') {
//       steps {
//         sh 'mvn clean test -f ./BinaryCalculatorWebapp/pom.xml'
//       }
//     }
//     stage ('build') {
//       steps {
//         sh 'mvn package -DskipTests -f ./BinaryCalculatorWebapp/pom.xml'
//       }
//     }
//     stage ('Deploy') {
//       steps {
//         sh 'echo "bye bye bye"'
//       }
//     }
//   }
// }
pipeline {
  agent any
  tools {
    maven 'maven' 
    // add Docker tool for building Docker images
    docker 'docker'
  }
  environment {
    PROJECT = "lab-4-deliverable"
    APP_NAME = "binary-calculator2"
    CLUSTER = "sofe3980u"
    CLUSTER_ZONE = "northamerica-northeast1-b"
    IMAGE_TAG = "gcr.io/${PROJECT}/${APP_NAME}"
    JENKINS_CRED = "310349070498-compute@developer.gserviceaccount.com"
  }
  stages {
    stage ('Init') {
      steps {
        sh 'echo "Start of Job"'
        sh 'ls -la'
      }
    }
    stage ('test') {
      steps {
        sh 'mvn clean test -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('build') {
      steps {
        sh 'mvn package -DskipTests -f ./BinaryCalculatorWebapp/pom.xml'
        // build Docker image and tag with the GCR image tag
        sh 'docker build -t ${IMAGE_TAG} .'
        // authenticate Docker to push to GCR using Jenkins credentials
        sh 'gcloud auth activate-service-account --key-file /var/lib/jenkins/creds.json'
        sh 'gcloud auth configure-docker'
        // push Docker image to GCR
        sh 'docker push ${IMAGE_TAG}'
      }
    }
    stage ('Deploy') {
      steps {
        // authenticate Kubernetes using Jenkins credentials
        sh 'gcloud auth activate-service-account --key-file /var/lib/jenkins/creds.json'
        sh 'gcloud container clusters get-credentials ${CLUSTER} --zone ${CLUSTER_ZONE} --project ${PROJECT}'
        // deploy Kubernetes manifests
        sh 'kubectl apply -f ./kubernetes/manifests'
      }
    }
  }
}
